modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/mahmudindev/mcmod-vanillaworld/issues"
license = "ARR"

[[mods]]
modId = "vanillaworld"
version = "${version}"
displayName = "Vanilla World"
authors = "mahmudindev"
description = '''
Add vanilla dimensions while keeping the original dimensions.
'''
logoFile = "assets/vanillaworld/icon.png"

[[dependencies.vanillaworld]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vanillaworld]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vanillaworld]]
modId = "worldportal"
mandatory = true
versionRange = "[0.0.3,)"
ordering = "NONE"
side = "SERVER"

[[dependencies.vanillaworld]]
modId = "dimensionfixer"
mandatory = true
versionRange = "[0.0.3,)"
ordering = "NONE"
side = "SERVER"

[[dependencies.vanillaworld]]
modId = "dimensionlink"
mandatory = true
versionRange = "[0.0.2,)"
ordering = "NONE"
side = "SERVER"
